AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/NumericPredicate:
  EnforcedStyle: comparison
