AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/NumericPredicate:
  EnforcedStyle: comparison

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Layout/LineLength:
  Exclude:
    - spec/**/*

Naming/FileName:
  Exclude:
    - lib/mailgun-rails.rb
